name: Trigger Pipeline ETL
on:
  push:
    branches: [ main ]

jobs:
  deploy-and-trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Conectar a la VM y actualizar el repositorio
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            cd ~/pipeline/proyecto
            git pull origin main
            TOKEN=$(curl -s -X POST "http://localhost:8080/auth/token" \
              -H "Content-Type: application/json" \
              -d '{"username": "admin", "password": "bHRsAENDRwAg8vqZ"}' | python3 -c "import sys, json; print(json.load(sys.stdin)['access_token'])")
            curl -X POST "http://localhost:8080/api/v2/dags/pipeline_etl/dagRuns" \
              -H "Content-Type: application/json" \
              -H "Authorization: Bearer $TOKEN" \
              -d '{"logical_date": null}'
